# -*- coding: utf-8 -*-
"""predict-using-pipeline.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jrkW44kVGDLTDgSejgNZeBAESYDrShrG
"""

import pickle
import numpy as np
with open ('./model.pkl','rb') as model_pkl:
  pipe = pickle.load(model_pkl)

test_input = np.array([2, 'male', 31.0, 0, 0, 10.5, 'S'],dtype=object).reshape(1,7)
predict_result = pipe.predict(test_input)

print('predict result' + str(test_input) + 'is' + str(predict_result))

